import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: "Vicente Moscuzza - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Rubik+Wet+Paint&display=swap" rel="stylesheet"></link>
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
